# smarti-ems/config.yaml
name: SMARTi EMS
version: "1.0.8"   # bump
slug: smarti_ems
arch: [amd64, aarch64, armv7]
ingress: true
ingress_entry: /
homeassistant_api: true
hassio_api: true
image: ghcr.io/prosono/{arch}-addon-smarti-ems
